spring.application.name=ch1

test.msg = read config

#nest Simple properties
obj.sname = chenheng
obj.sage = 88
#List properties
obj.hobby[0] = running
obj.hobby[1] = basketball
#Map Properties
obj.city.cid = dl
obj.city.cname = Dalian

#设定日志的默认级别为info
logging.level.root = info
#设定org包下日志的级别为warn
logging.level.org = warn
#设定com.example.ch1包下日志的级别为debug
logging.level.com.example.ch1 = debug

#指定日志输出到文件
# logging.file = my.log
#也可指定目录地址：
logging.file.path = /home/yingxinli/JavaLearning/ch1
#日志文件大小到达10MB时将自动生成一个新日志文件

#指定控制台日志格式
logging.pattern.console = %level %date{yyyy-MM-dd HH:mm:ss:SSS} %logger{50}.%M %L:%m%n
#指定日志文件格式
logging.pattern.file = %level %date{ISO8601} %logger{50}.%M %L:%m%n
# %level: 指定输出日志级别；%date：指定日志发生的时间，ISO8601表示标准日期，相当于yyyy-MM-dd HH:mm:ss:SSS
# %logger：指定输出Logger的名字，包名+类名，{n}限定了输出长度
# %M：指定日志发生时的方法名；%L：指定日志调用时所在的代码行，适用于开发调试，线上运行时会对性能有消耗
# %m：表示日志消息；%n：表示日志换行